import { FileType } from '../types';

export function getFileTypeFromExtension(extension: string): FileType {
  const ext = extension.toLowerCase().replace('.', '');
  
  const imageExts = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'bmp', 'ico'];
  if (imageExts.includes(ext)) return 'image';

  const docExts = ['pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'md'];
  if (docExts.includes(ext)) return 'document';

  const sheetExts = ['xls', 'xlsx', 'csv', 'ods', 'tsv'];
  if (sheetExts.includes(ext)) return 'spreadsheet';

  const presExts = ['ppt', 'pptx', 'key', 'odp'];
  if (presExts.includes(ext)) return 'presentation';

  const videoExts = ['mp4', 'mov', 'avi', 'mkv', 'webm', 'wmv'];
  if (videoExts.includes(ext)) return 'video';

  const audioExts = ['mp3', 'wav', 'ogg', 'm4a', 'flac', 'aac'];
  if (audioExts.includes(ext)) return 'audio';

  const codeExts = ['js', 'ts', 'jsx', 'tsx', 'html', 'css', 'json', 'py', 'go', 'rs', 'java', 'c', 'cpp', 'sh', 'sql', 'yaml', 'yml'];
  if (codeExts.includes(ext)) return 'code';

  const archiveExts = ['zip', 'rar', '7z', 'tar', 'gz', 'bz2'];
  if (archiveExts.includes(ext)) return 'archive';

  return 'other';
}

export function getFileTypeStyles(type: FileType): {
  bgLight: string;
  badgeBg: string;
  badgeText: string;
  iconColor: string;
  borderHover: string;
} {
  switch (type) {
    case 'image':
      return {
        bgLight: 'bg-emerald-50',
        badgeBg: 'bg-emerald-100',
        badgeText: 'text-emerald-700',
        iconColor: 'text-emerald-600',
        borderHover: 'hover:border-emerald-300',
      };
    case 'document':
      return {
        bgLight: 'bg-blue-50',
        badgeBg: 'bg-blue-100',
        badgeText: 'text-blue-700',
        iconColor: 'text-blue-600',
        borderHover: 'hover:border-blue-300',
      };
    case 'spreadsheet':
      return {
        bgLight: 'bg-teal-50',
        badgeBg: 'bg-teal-100',
        badgeText: 'text-teal-700',
        iconColor: 'text-teal-600',
        borderHover: 'hover:border-teal-300',
      };
    case 'presentation':
      return {
        bgLight: 'bg-amber-50',
        badgeBg: 'bg-amber-100',
        badgeText: 'text-amber-700',
        iconColor: 'text-amber-600',
        borderHover: 'hover:border-amber-300',
      };
    case 'video':
      return {
        bgLight: 'bg-rose-50',
        badgeBg: 'bg-rose-100',
        badgeText: 'text-rose-700',
        iconColor: 'text-rose-600',
        borderHover: 'hover:border-rose-300',
      };
    case 'audio':
      return {
        bgLight: 'bg-purple-50',
        badgeBg: 'bg-purple-100',
        badgeText: 'text-purple-700',
        iconColor: 'text-purple-600',
        borderHover: 'hover:border-purple-300',
      };
    case 'code':
      return {
        bgLight: 'bg-indigo-50',
        badgeBg: 'bg-indigo-100',
        badgeText: 'text-indigo-700',
        iconColor: 'text-indigo-600',
        borderHover: 'hover:border-indigo-300',
      };
    case 'archive':
      return {
        bgLight: 'bg-orange-50',
        badgeBg: 'bg-orange-100',
        badgeText: 'text-orange-700',
        iconColor: 'text-orange-600',
        borderHover: 'hover:border-orange-300',
      };
    default:
      return {
        bgLight: 'bg-slate-50',
        badgeBg: 'bg-slate-100',
        badgeText: 'text-slate-700',
        iconColor: 'text-slate-600',
        borderHover: 'hover:border-slate-300',
      };
  }
}

export function downloadFile(filename: string, contentUrlOrText?: string, mimeType: string = 'text/plain') {
  if (contentUrlOrText && (contentUrlOrText.startsWith('data:') || contentUrlOrText.startsWith('blob:') || contentUrlOrText.startsWith('http'))) {
    const a = document.createElement('a');
    a.href = contentUrlOrText;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  } else {
    // Generate text/blob download
    const content = contentUrlOrText || `File content for ${filename} - generated by CloudVault`;
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}

export function generateRandomId(prefix: string = 'item'): string {
  return `${prefix}_${Math.random().toString(36).substring(2, 9)}_${Date.now().toString(36)}`;
}
